### PR TITLE
Analysis of user's reactions

### LINKED ISSUE #6: Reacts > How do you react?
- How often do you use love reacts?
- What friends' posts are you most likely to react to?
- Is their a friend for whose posts you use a single react?

### PR DESCRIPTION
**Pull request by parimatrix**
I added two features
1. A plot of a count of user's reactions
2. Display of the top 10 user's friends whose posts are most liked/reacted to by the user.

Closes #6

### CODE REVIEW

**Comment by parimatrix** [comment]
Added the plots.
Would take time to make the data. Cause I will have to figure out how to replace people's names with dummy ones, as it's a normal sentence and not a JSON key value in the data.

**Comment by kaustubhhiware** [comment]
The plots are sure impressive.
Addressing your own itinerary mentioned on #6

>Show the variation of number of reactions over different time periods.

This will be another plot, where x axis is time, y is count, and there will be 5-6 "lines", each line denoting what react. 
Do you plan to do this in the same PR?

>Show the names of friends whose posts we reacted to the most, or top 5. Something like that. 
Do you wish to implement this?

Don't worry about points, if this PR has a lot of work put in, points will be given accordingly.
1 big PR will get the same points as 2 small ones.

**Comment by parimatrix** [comment]
Thanks. 
Okay, yeah. I will try to do the new plot in this PR only. Less number of PRs means less clutter.
Regarding, the top 10 friends, I already did implement it. It shows a list of top 10 friends on the command line.

**Comment by parimatrix** [comment]
I have added the plot for the cumulative count of different reactions, and the image too.
I have added all reactions including 'LIKE', though I feel we should omit that cause number of 'LIKE's is way too large as compared to other reactions and that kind of spoils the plot.

**Comment by kaustubhhiware** [comment]
Great work  ! :smile:
Only two things remain:
i) add sample json file
ii) update README [features](https://github.com/kaustubhhiware/facebook-archive#features).

As soon as you're done with these, I'll merge it in.

**Comment by parimatrix** [comment]
Readme Updated. 
One request, can we make a separate issue for adding the example JSON files. I find it would be really helpful if someone could handle that efficiently.  
If no, then I would try to do it then. Thanks! 😃

**Comment by kaustubhhiware** [comment]
Can't you just keep like 100 reacts from the file, and remove the names ?

You don't have to make your complete file anonymous. You could use regex matching to replace real people's name from your file, it seems too trivial to add another issue just to create an example file.

**Comment by parimatrix** [comment]
Okay, sure. I will do that

**Comment by parimatrix** [comment]
@xprilion Done that. Added in readme too, and the image in the images. :)

**Comment by kaustubhhiware** [comment]
Since no other mentor has objections, merging this in.

**Comment by kaustubhhiware** [comment]
@parimatrix , I was seeing the `reactions as a function of month` plot, the reacts at month 1 and 10 (Feb and Nov) are lowest. Can you try to think why?

I was wondering we could have some insights from this plot. The other plots are pretty straight forward.

**Comment by parimatrix** [comment]
@kaustubhhiware Well, I can think of no explanation for Feb.
For Nov and also May (that's low too), in my case, it's pretty clear what affects it, The One and Only EndSemester Exams :P. I guess so.
But the reason would be different for different people. Maybe among students, it may be common, but don't know for others.  :(

**Pull request merged**
