### PR TITLE
Add support for json data visualization

### PR DESCRIPTION
**Pull request by farhaanbukhsh**
This commit adds the script to support json data visualization,
this works on the fact that the data downloded is in JSON format.

This gives the trends like the most messages in which year, or which month of the year you text the most etc.

Signed-off-by: Farhaan Bukhsh <farhaan.bukhsh@gmail.com>

### CODE REVIEW

**Comment by techytushar** [comment]
Few suggestion from my side:  
* Instead of asking for the exact location of message folder we should only ask for for the location of the extracted folder, because the same schema is being followed in the `plot_friends.py` script  
* If I don't give the location of the folder while running the script, then it gives an error, like if I run `python messages_json_plot.py` then it gives an error. Instead it should input location of the folder.
* Please add some sample data in the examples folder so that the user can run the scripts without his/her facebook data.
* Please also add pandas to `requirements.txt` file.

**Comment by kaustubhhiware** [comment]
I was thinking we should either have all scripts or all classes, not both. Need to standardise this.

Also, no need to make new file, just call this plot_messages.py.

Could you please add a sample json file like @techytushar did in his previous PR?

**Comment by farhaanbukhsh** [comment]
@kaustubhhiware I don't know I feel that if we write it in terms of classes there can be a lot of reusable code that can be seen, and also IMHO I feel it gives the code a structure but again it's your call. 😄 

@techytushar Thanks for the feed back will try to include sample data but I feel it will be great to let them download and use their data.

**Comment by farhaanbukhsh** [comment]
Ahh my bad I should have put the message for `message` location

**Comment by techytushar** [comment]
@farhaanbukhsh Yes, now its working, but we should take the users facebook data folder address insted of message folder, as this is the convention going on in all other scripts. :slightly_smiling_face:

**Comment by farhaanbukhsh** [comment]
@techytushar fixed it :smile:  thanks a lot for suggestion, can @xprilion and @kaustubhhiware and @roopalJazz check it too?

**Comment by farhaanbukhsh** [comment]
should I merge this in guys? :rofl: been real long?

**Comment by farhaanbukhsh** [comment]
Merging this in 😄

**Pull request merged**
