### PR TITLE
Created --to flag and --from flag to plot_friends.py

### LINKED ISSUE #28: Friends > Plot friends only since the last year
## Description
Extend functionality of plot_friends.py to specify from and to period. Currently doing for all time. 
Something of the type: `python plot_friends.py --from 2018-12-01`, should support both `--from` and `--to` flags, both optional.

## Steps to reproduce (Incase of a bug)
NA

### Update [Required]
- [ ] Support `--from` and `--to` flags in plot_friends.py
### Enhancement to Update [Optional]
- [x] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4-5 hours after having an idea of original code

### LINKED ISSUE #29: README python version issue
## Description
The README file indicates the code uses python 2.7.

However, when I tried to run `plot_friends.py`, the given example gives an error. 

```
$ python plot_friends.py
Enter facebook archive extracted location: ./examples
Traceback (most recent call last):
  File "plot_friends.py", line 87, in <module>
    friends(loc)
  File "plot_friends.py", line 22, in friends
    loc = input('Enter facebook archive extracted location: ')
  File "<string>", line 1
    ./examples
    ^
SyntaxError: invalid syntax
```
This is because the python 2.7 `input` function expects a python expression that can be executed. 

## Mocks
N/A

## Steps to reproduce (Incase of a bug)
- Use python 2.7 
- Install required dependency `pip install -r requirements.txt`
- run `python plot_friends`
- input `./exmaples`

### Update [Required]
Choose Either one of the solutions:
- Change to python 3.x on the README file
- Change to `raw_input` instead of `input`
- Use command line argument instead of having the user input it manually (recommended)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

### PR DESCRIPTION
**Pull request by GalenWong**
# Created --to flag and --from flag for plot_friends.py
fix #28 
fix #29 
- Added --to and --from flag to plot_friends.py
- Refactored and renamed functions
- Remove unused variable declaration
- Stylistic fixes

### Description
Extend functionality of plot_friends.py to specify from and to period. Currently doing for all time.
Something of the type: `python plot_friends.py --from 2018-12-01`, should support both `--from` and `--to` flags, both optional.
Fixes # [ISSUE]

### Type of Change:
- Code

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Normal test cases
```
python plot_friends examples
python plot_friends examples --from 2018-6-11
python plot_friends examples --to 2018-6-11
python plot_friends examples --from 2018-2-11 --to 2018-6-11
```
Test cases that should give error
```
python plot_friends examples --from
python plot_friends --to
```

### Checklist:

- [x] I have ensured my PR satisfies the checklist mentioned in [CONTRIBUTING.md](CONTRIBUTING.md).
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (need another PR)
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works ( no tests available in this repo )
- [ ] New and existing unit tests pass locally with my changes ( no tests available in this repo )
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by kaustubhhiware** [comment]
LGTM.

* Cover corner cases. What if the user provides a date beyond today? Yoiu could try handling that case, by tracking a minimum and maximum date. This is the current output for the corner case.
```
python plot_friends.py ../facebook-kaustubhhiware/ --from 2018-12-10
Traceback (most recent call last):
  File "plot_friends.py", line 147, in <module>
    plot_friends_by_date(friends_list)
  File "plot_friends.py", line 28, in plot_friends_by_date
    firstdate = dates[0]
IndexError: list index out of range
```

* Add instructions how to execute this in relevant section of README (in Usage section)
* Add python version.

That's it. Once these changes are done, I'll merge right away.

**Comment by GalenWong** [comment]
@kaustubhhiware Thank you for your comment.

That bug actually implies another underlying issue. This error occurs since the `plot_friends_by_date` function tries to access the first element in the first place. This means that the original function assumes that the `friend_list` being passed in is **not empty**. If somebody passed in an empty archive with `friends.json` holding this following data,
```
{
    "friends": []
}
```
then the program also gives the same error. 

We need to implement a check somehow to avoid plotting out empty lists. Since that is a new "feature", how do you think it should behave? 

I would suggest changing the implementation of how `firstdate` and `maxdays` are being calculated. What if the list only has one element? I would also suggest this changes should sit in another PR.

**Comment by kaustubhhiware** [comment]
I'm leaning more towards making these changes within the same PR, but up to you.
If you think the diff (lines changed) is going to be huge, go for another PR.

Else, you could make the changes in `firstdate` and `maxdays` within this PR. That is your call. Thanks for pointing out some of the initial biases.

**Comment by GalenWong** [comment]
@kaustubhhiware understood and thank you for the feedback.

I will look into it more once I have more time.

**Comment by kaustubhhiware** [comment]
(Continued)
If the provided list is empty as you pointed out, I think we should just display "You have 0 friends. No plots for you" or something along those lines, and exit the script.

This check should be put before `firstdate  = dates[0]`.

**Comment by kaustubhhiware** [comment]
Kindly update the usage of flags in README, add instructions for the archive_path flag as well.

Let me know when the PR is ready for a review.

**Comment by GalenWong** [comment]
Sorry, I have been quite busy lately. I will resume my work beginning this weekend. My apology for the delay.

**Comment by kaustubhhiware** [comment]
Not a problem :smile . I just wanted to make sure you're still working, given that most of the work has already been done.

**Comment by kaustubhhiware** [comment]
Not a problem :smile:
I wanted to ensure you're still working, since most of the work is already completed.

**Comment by GalenWong** [comment]
@kaustubhhiware I updated the README in the last commit. I also changed the way that x-axis is being calculated. It was calculated from `datetime.datetime.now()`. It is now calculated based on the last date in the sorted order.

**Comment by kaustubhhiware** [comment]
Merging this in since it's long overdue.

**Pull request merged**
